package com.github.njuro.jard.base;

import java.util.List;
import org.mapstruct.*;
import org.springframework.stereotype.Component;

/**
 * Base mapper for mapping instances of {@link BaseEntity} and {@link BaseDto} and vice versa.
 * Implementations of mapping methods are generated by MapStruct library on project compile.
 */
@Component
public interface BaseMapper<E extends BaseEntity, D extends BaseDto> {

  /**
   * Mapping config to be used by all inheriting mappers (needs to be set explicitly via {@link
   * Mapper#config()}
   */
  @MapperConfig(
      unmappedTargetPolicy = ReportingPolicy.IGNORE,
      mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG,
      componentModel = "spring",
      injectionStrategy = InjectionStrategy.CONSTRUCTOR)
  class Config {}

  D toDto(E entity);

  List<D> toDtoList(List<E> entityList);

  E toEntity(D dto);

  E toExistingEntity(D dto, @MappingTarget E existingEntity);

  List<E> toEntityList(List<D> dtoList);
}
