package com.github.njuro.jard.base;

import java.util.List;
import org.mapstruct.*;
import org.springframework.stereotype.Component;

/**
 * Base mapper for mapping instances of {@link BaseEntity} and {@link BaseDto} and vice versa.
 * Implementations of mapping methods are generated by MapStruct library on project compile.
 */
@Component
public interface BaseMapper<ENTITY extends BaseEntity, DTO extends BaseDto> {

  /**
   * Mapping config to be used by all inheriting mappers (needs to be set explicitly via {@link
   * Mapper#config()}
   */
  @MapperConfig(
      unmappedTargetPolicy = ReportingPolicy.IGNORE,
      mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG,
      componentModel = "spring",
      injectionStrategy = InjectionStrategy.CONSTRUCTOR)
  class Config {}

  DTO toDto(ENTITY entity);

  List<DTO> toDtoList(List<ENTITY> entityList);

  ENTITY toEntity(DTO dto);

  ENTITY toExistingEntity(DTO dto, @MappingTarget ENTITY existingEntity);

  List<ENTITY> toEntityList(List<DTO> dtoList);
}
